apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test:
    steps:
      - name: Checkout code
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Run tests with custom action
        uses: ./.cloudbees/actions/test-node

  build:
    needs: test
    uses: ./.cloudbees/workflows/build-reusable.yaml
